spring.application.name=Omni_Bridge
spring.config.import=optional:file:.env[.properties]

# App Config
app.base.url=${APP_BASE_URL:http://localhost:8080}
app.frontend.url=${APP_FRONTEND_URL:http://localhost:3000}
app.admin-key=${ADMIN_SIGNUP_KEY}
spring.profiles.active=dev
server.port=8081

# JWT Config
jwt.secret=${JWT_SECRET_KEY}
jwt.expiration-ms=3600000

# OTP Config
otp.expiration-ms=300000
otp.cleanup-rate-ms=60000
otp.length=6
ott.token.expiry.seconds=300
ott.cleanup-rate-ms=300000

# Mail Configuration
spring.mail.from=${MAIL_USERNAME:no-reply@localhost}
brevo.api.key=${BREVO_API_KEY}

# Rate Limiting Config
rate-limit.duration=1
rate-limit.register=3
rate-limit.auth=20
rate-limit.otp=5
rate-limit.ott=5
rate-limit.report=60

# Logging Config
spring.output.ansi.enabled=always
server.forward-headers-strategy=framework
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%-5level){yellow} %clr([%15.15t]){cyan} %clr(%-40.40logger{39}){blue} : %m%n